Model:
  AudioNet:
    n_layer: 3
    channels: [15, 40, 60]
    input_drop: 0.3
    hidden_dim: 2000
    latent_dim: 300
Data:
  sr: 44100
  time_duration: 2
  time_stride: 1
  window_size: 0.025
  window_stride: 0.01
  n_mels: 40
  slicing : 40
Train:
  train_ratio: 0.8
  batch_size: 128
  epochs: 300
  lr: 1e-4
  seed: 42

