data:
  sr: 64
  time_duration: 2
EEG:
  in_channels: 1
  channel_size: 40
  temporal_conv_size: 25
  spatial_conv_size: 60
  avg_kernel: 25
  avg_stride: 5
  dropout: 0.3
  input_drop: 0.3
  num_head: 10
  num_attention: 6
  expansion : 4
  hidden_dim: 500
  latent_dim: 300
train:
  train_ratio : 0.8
  batch_size: 128
  num_epoch: 300
  lr: 0.0005
  seed: 42
